// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMfLG-wEGfID3hM1r8Bo9gHWtXCx4y7Sw',
    appId: '1:687931871146:web:66f2e24a4565cbca70a5d3',
    messagingSenderId: '687931871146',
    projectId: 'autovidcraft-d78a3',
    authDomain: 'autovidcraft-d78a3.firebaseapp.com',
    storageBucket: 'autovidcraft-d78a3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiD_XOBGuiQ4AXBXd4qEpTgAYZNWNC0OU',
    appId: '1:687931871146:android:650bbc8401a99a3470a5d3',
    messagingSenderId: '687931871146',
    projectId: 'autovidcraft-d78a3',
    storageBucket: 'autovidcraft-d78a3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARCTALoUWKxJbIGFjuR6dUCiI8tTaLs-k',
    appId: '1:687931871146:ios:777a8f67d1c4048270a5d3',
    messagingSenderId: '687931871146',
    projectId: 'autovidcraft-d78a3',
    storageBucket: 'autovidcraft-d78a3.firebasestorage.app',
    iosBundleId: 'com.example.auto',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAMfLG-wEGfID3hM1r8Bo9gHWtXCx4y7Sw',
    appId: '1:687931871146:web:17a02255a5a1033470a5d3',
    messagingSenderId: '687931871146',
    projectId: 'autovidcraft-d78a3',
    authDomain: 'autovidcraft-d78a3.firebaseapp.com',
    storageBucket: 'autovidcraft-d78a3.firebasestorage.app',
  );
}
